// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv8l1SXGKWKhM5biNAduLFLE5K1hJzzLE',
    appId: '1:969859247339:web:8b950900d734455205e2ae',
    messagingSenderId: '969859247339',
    projectId: 'clearance-84707',
    authDomain: 'clearance-84707.firebaseapp.com',
    storageBucket: 'clearance-84707.appspot.com',
    measurementId: 'G-6J0XCZG62S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1myZd_WBPCPcAVR6TX-dE6uKLyeJTsnM',
    appId: '1:969859247339:android:23ba75896ea435a905e2ae',
    messagingSenderId: '969859247339',
    projectId: 'clearance-84707',
    storageBucket: 'clearance-84707.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADTcBGcPVzaXpkh6IVrDd9iglwC29IZjU',
    appId: '1:969859247339:ios:9ce936af392745d805e2ae',
    messagingSenderId: '969859247339',
    projectId: 'clearance-84707',
    storageBucket: 'clearance-84707.appspot.com',
    iosBundleId: 'com.example.clearanceProcessingSystem',
  );
}
